version: '3.8'
services:
  database:
    container_name: postgres
    image: aa8y/postgres-dataset
    restart: always
    environment:
      POSTGRES_USER: root
      POSTGRES_PASSWORD: root
      POSTGRES_DB: test_db
    ports:
      - "5432:5432"
  dbt:
    build: .
    tty: true
    volumes:
      - ./dbt_hw:/dbt_hw
      - ./.dbt:/root/.dbt
    depends_on:
      - database
    ports:
      - "5444:5444"
  pgadmin:
    container_name: pgadmin
    image: dpage/pgadmin4
    restart: always
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@admin.com
      PGADMIN_DEFAULT_PASSWORD: root
    ports:
      - "5050:80"